# Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit.
[colors]
foreground={{fg.nohash}}
background={{bg.nohash}}
selection-foreground={{bg.nohash}}
selection-background={{primary.nohash}}
urls={{secondary.nohash}}

regular0={{black.nohash}}
regular1={{red.nohash}}
regular2={{green.nohash}}
regular3={{yellow.nohash}}
regular4={{blue.nohash}}
regular5={{magenta.nohash}}
regular6={{cyan.nohash}}
regular7={{white.nohash}}

bright0={{bright_black.nohash}}
bright1={{bright_red.nohash}}
bright2={{bright_green.nohash}}
bright3={{bright_yellow.nohash}}
bright4={{bright_blue.nohash}}
bright5={{bright_magenta.nohash}}
bright6={{bright_cyan.nohash}}
bright7={{bright_white.nohash}}
