# Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit.
# Sourced by hyprland.conf (colours only; layout stays in the main config).
general {
    col.active_border = rgba({{primary.nohash}}ee) rgba({{secondary.nohash}}ee) 45deg
    col.inactive_border = rgba({{surface.nohash}}aa)
}
