-- Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit.
-- Loaded by hyprland.lua (colours only; layout stays in the main config).
return {
    active_border   = "rgba({{primary.nohash}}ee)",
    active_border2  = "rgba({{secondary.nohash}}ee)",
    inactive_border = "rgba({{surface.nohash}}aa)",
}
