# Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit.
foreground            {{fg}}
background            {{bg}}
selection_foreground  {{bg}}
selection_background  {{primary}}
cursor                {{primary}}
cursor_text_color     {{bg}}
url_color             {{secondary}}
active_border_color   {{primary}}
inactive_border_color {{surface}}
bell_border_color     {{tertiary}}

active_tab_foreground   {{bg}}
active_tab_background   {{primary}}
inactive_tab_foreground {{fg_dim}}
inactive_tab_background {{bg_alt}}
tab_bar_background      {{bg}}

color0  {{black}}
color8  {{bright_black}}
color1  {{red}}
color9  {{bright_red}}
color2  {{green}}
color10 {{bright_green}}
color3  {{yellow}}
color11 {{bright_yellow}}
color4  {{blue}}
color12 {{bright_blue}}
color5  {{magenta}}
color13 {{bright_magenta}}
color6  {{cyan}}
color14 {{bright_cyan}}
color7  {{white}}
color15 {{bright_white}}
