// Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit.
// Included by niri's config.kdl (colours only; layout stays in the main config).
layout {
    focus-ring {
        active-color "{{primary}}"
        inactive-color "{{surface}}"
    }
}
