/* Generated by theme-apply from ~/.config/theme/theme.conf -- do not edit. */
* {
    bg:        {{bg}}ee;
    bg-alt:    {{bg_alt}};
    surface:   {{surface}};
    overlay:   {{overlay}};
    fg:        {{fg}};
    fg-dim:    {{fg_dim}};
    primary:   {{primary}};
    secondary: {{secondary}};
    urgent:    {{red}};
}
